Add docker file and rework appsettings
LT-Students/DigitalOffice-ProjectService pull request #35
Opened 2021-03-18 15:41 UTC by djino97

2021-03-18 16:21 UTC, DarkFelas requested changes

2021-03-18 16:21 UTC, DarkFelas commented on src/ProjectService/appsettings.Production.json
> +  "Logging": {
remove Logging section

2021-03-18 16:21 UTC, DarkFelas commented on src/ProjectService/appsettings.Development.json
>        "Microsoft": "Warning",
remove Logging section

2021-03-18 16:21 UTC, DarkFelas commented on src/ProjectService/appsettings.json
> +    "AccessValidatorCheckRightsServiceURL": "CheckRightsService",
Check example in UserService

2021-03-18 23:21 UTC, djino97 commented on src/ProjectService/appsettings.Production.json
> +  "Logging": {
Fixed

2021-03-18 23:21 UTC, djino97 commented on src/ProjectService/appsettings.Development.json
>        "Microsoft": "Warning",
Fixed

2021-03-18 23:22 UTC, djino97 commented on src/ProjectService/appsettings.json
> +    "AccessValidatorCheckRightsServiceURL": "CheckRightsService",
Renamed endpoints and values. Fixed.

2021-03-19 23:45 UTC, DarkFelas approved these changes

2021-03-19 23:45 UTC, merged