Update get project endpoint
LT-Students/DigitalOffice-ProjectService pull request #47
Opened 2021-04-28 16:58 UTC by KostinP

2021-05-04 19:24 UTC, KostinP commented on src/ProjectService.Business/Commands/GetProjectByIdCommand.cs
> +                    //TODO Add mapper
Not edit. Add mapper for map from IGetDepartmentResponse to DepartmentInfo

2021-05-04 19:25 UTC, KostinP commented on src/ProjectService.Broker/GetProjectInfoConsumer.cs
> +            var filter = new GetProjectFilter { ProjectId = projectId };
Repository was changed

2021-05-05 14:36 UTC, djino97 commented on src/ProjectService.Mappers/ResponsesMappers/ProjectExpandedResponseMapper.cs
> +﻿using LT.DigitalOffice.ProjectService.Mappers.ModelsMappers.Interfaces;
need rename mapper by new scheme

2021-05-05 14:36 UTC, djino97 commented on src/ProjectService.Models.Dto/Requests/Filters/GetProjectFilter.cs
> +        [FromQuery(Name = "projectId")]
Fix format query

2021-05-05 14:36 UTC, djino97 commented on src/ProjectService.Mappers/ResponsesMappers/ProjectExpandedResponseMapper.cs
> +﻿using LT.DigitalOffice.ProjectService.Mappers.ModelsMappers.Interfaces;
Simple ProjectResponseMapper

2021-05-05 14:36 UTC, djino97 commented on src/ProjectService/Controllers/ProjectController.cs
>          [HttpGet("getProjectById")]
simple get

2021-05-05 14:36 UTC, djino97 commented on src/ProjectService/Controllers/ProjectController.cs
>              [FromServices] IGetProjectByIdCommand command,
simple Get

2021-05-05 14:36 UTC, djino97 commented on src/ProjectService.Models.Dto/Responses/ProjectExpandedResponse.cs
>      {
simple ProjectResponse

2021-05-05 14:36 UTC, djino97 commented on src/ProjectService.Business/Commands/GetProjectByIdCommand.cs
> +using System.Linq;
simple GetProjectCommand

2021-05-05 14:38 UTC, BelehovEgor requested changes

2021-05-05 14:38 UTC, BelehovEgor commented on src/ProjectService.Business/Commands/GetProjectByIdCommand.cs
>      public class GetProjectByIdCommand : IGetProjectByIdCommand
Can you name it GetProjectCommand?

2021-05-05 14:38 UTC, BelehovEgor commented on src/ProjectService.Business/Commands/GetProjectByIdCommand.cs
> +                    //TODO Add mapper
and why you can't do it?

2021-05-05 14:38 UTC, BelehovEgor commented on src/ProjectService.Data/UserRepository.cs
> +                predicate.Or(u => !u.IsActive);
Are you sure about this predicate? it looks like u.ProjectId == projectId && u.IsActive || !u.IsActive, so if user is inactive and his id not equal to porjectId we took it too

2021-05-05 14:38 UTC, BelehovEgor commented on src/ProjectService.Models.Broker/Responses/IGetUsersDataResponse.cs
> +        List<UserData> UsersData { get; }
maybe better use IList

2021-05-05 14:38 UTC, BelehovEgor commented on src/ProjectService.Models.Dto/Models/ProjectUser/ProjectUserInfo.cs
>      public class ProjectUserInfo
why don't we need ProectId here?

2021-05-05 14:38 UTC, BelehovEgor commented on test/ProjectService.Broker.UnitTests/GetProjectInfoConsumerTests.cs
> +                _repository.Verify(x => x.GetProject(It.IsAny<GetProjectFilter>()), Times.Once);
I don't think that using It.IsAny in verify  is good

2021-05-05 14:38 UTC, BelehovEgor commented on test/ProjectService.Business.UnitTests/Commands/EditProjectByIdCommandTests.cs
>          private IEditProjectByIdCommand command;
use _

2021-05-11 18:56 UTC, KostinP commented on src/ProjectService.Business/Commands/GetProjectByIdCommand.cs
> +                    userIds = projectUsers.Where(x => x.IsActive == true).Select(x => x.Id).Distinct().ToList();
Bug, not id, UserId

2021-05-11 18:58 UTC, KostinP commented on src/ProjectService.Mappers/ResponsesMappers/ProjectExpandedResponseMapper.cs
> +﻿using LT.DigitalOffice.ProjectService.Mappers.ModelsMappers.Interfaces;
Why?

2021-05-11 18:59 UTC, KostinP commented on src/ProjectService.Models.Dto/Responses/ProjectExpandedResponse.cs
>      {
Why? ProjectResponse already exist

2021-05-12 11:45 UTC, djino97 commented on src/ProjectService.Models.Dto/Responses/ProjectExpandedResponse.cs
>      {
see this as look like in UserService

2021-05-12 11:45 UTC, djino97 commented on src/ProjectService.Mappers/ResponsesMappers/ProjectExpandedResponseMapper.cs
> +﻿using LT.DigitalOffice.ProjectService.Mappers.ModelsMappers.Interfaces;
see this as look like in UserService

2021-05-12 15:41 UTC, KostinP commented on src/ProjectService.Mappers/ResponsesMappers/ProjectExpandedResponseMapper.cs
> +﻿using LT.DigitalOffice.ProjectService.Mappers.ModelsMappers.Interfaces;
Renamed

2021-05-13 16:52 UTC, djino97 approved these changes

2021-05-13 17:36 UTC, BelehovEgor approved these changes

2021-05-14 08:43 UTC, TIove approved these changes

2021-05-14 13:44 UTC, MariyaSin approved these changes

2021-05-17 14:15 UTC, merged